name: Release plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build
          npm run deploy
          mkdir obsidian-solo-rpg-toolkit
          cp dist/* obsidian-solo-rpg-toolkit
          zip ./dist/obsidian-solo-rpg-toolkit.zip obsidian-solo-rpg-toolkit/*

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/main.js dist/manifest.json dist/styles.css dist/obsidian-solo-rpg-toolkit.zip
